"""empty message

Revision ID: 71518b78bb18
Revises: 5b7082a03466
Create Date: 2022-04-01 16:25:43.553902

"""

# revision identifiers, used by Alembic.
revision = '71518b78bb18'
down_revision = '5b7082a03466'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
